apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-r26a
  namespace: mdsaud-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload@sha256:63eae5c7ec74acaa299f37194f1740a58a83dc24388c2b8ebb9afdb9d2f89bf1
        name: main
        resources: {}
status: {}
