apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-sample-l6ti
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-sample-l6ti
    app.kubernetes.io/part-of: my-app-1
  name: java-sample-l6ti
  namespace: mdsaud-tenant
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: java-sample-l6ti
    weight: 100
status: {}
